name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Setup chrome driver (for Selenium)
      uses: nanasess/setup-chromedriver@master
    - run: |
      export DISPLAY=:99
      chromedriver --url-base=/wd/hub &
      sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.5
        bundle install
        bundle exec rake
